[package]
name = "rann-traits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.4"
num-traits = "0.2.18"

[dev-dependencies]
rann-base = { path = "../rann-base" }
